name: Deploy to Cloud Run and Firebase Hosting

on:
  workflow_dispatch:
    inputs:
      os:
        description: "Runner OS (ubuntu-latest | macos-latest | windows-latest)"
        required: false
        default: windows-latest
  push:
    tags: [ 'deploy-*' ]

jobs:
  deploy:
    runs-on: ${{ inputs.os || 'windows-latest' }}
    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Restore
        shell: pwsh
        run: dotnet restore HRHelper.sln

      - name: Build
        shell: pwsh
        run: dotnet build HRHelper.sln -c Release --no-restore

      - name: Set up gcloud
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ env.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true

      - name: Deploy to Cloud Run (source)
        shell: pwsh
        run: >-
          gcloud run deploy hrhelper
          --source .
          --region $env:CLOUD_RUN_REGION
          --platform managed
          --allow-unauthenticated
          --set-env-vars ADMIN_PASSWORD=${{ secrets.ADMIN_PASSWORD }}

      - name: Deploy Firebase Hosting
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.GCP_SA_KEY }}
          projectId: ${{ env.GCP_PROJECT_ID }}
          channelId: live
    env:
      GCP_PROJECT_ID: hrhelper-57162
      CLOUD_RUN_REGION: us-central1
